### ISSUE TITLE
Error when Login  {'errors': [{'message': 'Exceed request rate limit!', 'locations': [{'line': 2, 'column': 3}], 'path': ['pwdLogin'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'code': 'IMEAN_ERROR'}}}], 'data': None}

### ISSUE THREAD

**Issue by QinghongLin** [iMeanAI/WebCanvas#28]
Hi when I try to login in my linux system.

export GRAPHQL_USERNAME='username'
export GRAPHQL_PASSWORD='passcode'

I meet such an error;

{'errors': [{'message': 'Exceed request rate limit!', 'locations': [{'line': 2, 'column': 3}], 'path': ['pwdLogin'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'code': 'IMEAN_ERROR'}}}], 'data': None}

Do you know what happen in this case?

Thanks you :)

**Comment by QinghongLin** [comment]
{'errors': [{'message': 'Exceed request rate limit!', 'locations': [{'line': 2, 'column': 3}], 'path': ['pwdLogin'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'code': 'IMEAN_ERROR'}}}], 'data': None}
Traceback (most recent call last):
  File "/home/qinghong/WebCanvas/data/dataset_io.py", line 197, in <module>
    client.login()
  File "/home/qinghong/WebCanvas/data/dataset_io.py", line 40, in login
    if 'data' in response_json and 'pwdLogin' in response_json['data']:
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by han032206** [comment]
> Hi when I try to login in my linux system.
> 
> export GRAPHQL_USERNAME='username' export GRAPHQL_PASSWORD='passcode'
> 
> I meet such an error;
> 
> {'errors': [{'message': 'Exceed request rate limit!', 'locations': [{'line': 2, 'column': 3}], 'path': ['pwdLogin'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'code': 'IMEAN_ERROR'}}}], 'data': None}
> 
> Do you know what happen in this case?
> 
> Thanks you :)

Hi Qinghong, the error is caused by exceeding the rate limit for calling the data download API in a minute. Please check the code to ensure there aren’t multiple redundant or repeated download requests happening within the same time frame. If that’s not the case, could you please email me your registered email address so we can check the specific cause in more detail?

**Comment by QinghongLin** [comment]
@han032206  Hi! I have checked and there is no multiple redundant requests. (This happened when I first try)
My email address is `kevin.qh.lin@gmail.com`.

**Comment by han032206** [comment]
> @han032206 Hi! I have checked and there is no multiple redundant requests. (This happened when I first try) My email address is `kevin.qh.lin@gmail.com`.

Hi Qinghong, I've tried with your auth token to download the data, and the download looks fine to me. Maybe you can try it again, or just download the data through huggingface and play with it. Also, please note that an updated version of the dataset will be released on Hugging Face soon, so be sure to keep track of the new version to run your experiments accordingly.
